// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIGentTsjOoaknkIJ6pNxbhczzK5stTZE',
    appId: '1:427725112248:web:359f54c759dcc33ad4854d',
    messagingSenderId: '427725112248',
    projectId: 'necstaff-amplify',
    authDomain: 'necstaff-amplify.firebaseapp.com',
    storageBucket: 'necstaff-amplify.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtdXV8TCF6edTZlfd45PE0AMAHir9OWgs',
    appId: '1:427725112248:android:b3ba95fa242c7511d4854d',
    messagingSenderId: '427725112248',
    projectId: 'necstaff-amplify',
    storageBucket: 'necstaff-amplify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkQTUx6oReKiRoHNX5pNwb-qu4ZlcbO6g',
    appId: '1:427725112248:ios:01485a1c01b8f14cd4854d',
    messagingSenderId: '427725112248',
    projectId: 'necstaff-amplify',
    storageBucket: 'necstaff-amplify.appspot.com',
    iosBundleId: 'com.example.necstaff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkQTUx6oReKiRoHNX5pNwb-qu4ZlcbO6g',
    appId: '1:427725112248:ios:01485a1c01b8f14cd4854d',
    messagingSenderId: '427725112248',
    projectId: 'necstaff-amplify',
    storageBucket: 'necstaff-amplify.appspot.com',
    iosBundleId: 'com.example.necstaff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIGentTsjOoaknkIJ6pNxbhczzK5stTZE',
    appId: '1:427725112248:web:5593b264973b5353d4854d',
    messagingSenderId: '427725112248',
    projectId: 'necstaff-amplify',
    authDomain: 'necstaff-amplify.firebaseapp.com',
    storageBucket: 'necstaff-amplify.appspot.com',
  );

}